### PR TITLE
Copy and pasting entire TODO's 

### PR DESCRIPTION
**Pull request by atidyshirt**
I could have forgotten things! (Sorry in a bit of a rush this week and pretty new to making pull requests), couldn't figure out how to pull changes from the main repo over to the forked repository.

### CODE REVIEW

**Comment by kraanzu** [comment]
It does not seem to conflict with anything so Ig we're good :)
Thanks for your work @atidyshirt!

**Comment by atidyshirt** [comment]
I am out for the afternoon, but will do that when I get back 👍

**Comment by kraanzu** [comment]
Oki Dokie :)

**Comment by atidyshirt** [comment]
@kraanzu before merging, I think I have found a bug with this patch:

We can have a recursive callback loop that will cause the app to crash. This happens when we `yank` a todo and then paste it as a sub-node of itself, then it recursively calls until it hits the call stack limit.

Might have to clear and sign more properties than just the parent... I will look into this when I have some free time 💭

**Comment by kraanzu** [comment]
Hey @atidyshirt ,

I see. Makes sense! All this recursion stuff can get messy sometimes lol. Thanks for testing various cases tho!
I should add a test suite. It can come in handy :)

**Comment by kraanzu** [comment]
Hey @atidyshirt , I just realized that there might be a very simple solution for this :smile: 

You might have already noticed the [`commit`](https://github.com/kraanzu/dooit/blob/8f11c1e1a45298f617219aef60f584c0f8b1a414/dooit/api/todo.py#L235) function in `todo.py` which returns `List[Tuple[str, Optional[List[....]]]]` in order to be stored in the local computer

And then there's [`from_data`](https://github.com/kraanzu/dooit/blob/8f11c1e1a45298f617219aef60f584c0f8b1a414/dooit/api/todo.py#L270) function in order to fill the data into the `Todo` object

What I am trying to say here is, we can store the returned data from `commit` in the `Virtual Clipboard` and then use it later to create the todo. This shouldn't create any issues.

```python

def _insert(self, child: bool = True):
    if child:
        todo = self.add_child()
    else:
        todo = self.add_sibling()

    todo.from_data(Storage.clipboard)
```

Lemme know your thoughts on this

**Comment by atidyshirt** [comment]
@kraanzu that is a much better approach, I did not look into the commit and from data functions, I am much more in favor of this option

**Pull request closed without merging**
