### PR TITLE
Misc Features

### PR DESCRIPTION
**Pull request by SitiSchu**
As discussed in https://github.com/kraanzu/dooit/discussions/163

### CODE REVIEW

**Comment by kraanzu** [comment]
Thanks for the additions, Can you also add extra config options to the Wiki as well? :smiley:

**Comment by SitiSchu** [comment]
Can do, I'll need access first though, I suppose editing is currently restricted to collaborators only

**Comment by kraanzu** [comment]
Ah, Lemme check

**Comment by kraanzu** [comment]
Added you to `collaborators` 
Accept the invite and then you should be able to edit the wiki :)

**Comment by kraanzu** [comment]
Heyy @SitiSchu, totally forgot but can you also update the CHANGELOG :)
Thanks

**Comment by SitiSchu** [comment]
Could've seen that myself, whoops. Will just skip the PR for that and push to develop directly I suppose.

**Pull request merged**
