### PR TITLE
Add Homebrew installation method to README.md

### PR DESCRIPTION
**Pull request by superatomic**
Due to the successful merge of https://github.com/Homebrew/homebrew-core/pull/104251, Dooit is now part of the `homebrew/core` repository and can be installed by running:

```shell
brew install dooit
```

This pull request adds this information to the installation section of `README.md` that explains how to install dooit with Homebrew.

### CODE REVIEW

**Comment by kraanzu** [comment]
Hey there! 
Thank you so much for this PR.. I had no idea that homebrew worked like AUR
Quick question: Do I need to maintain the package or will it fetch the latest release from github?

**Comment by superatomic** [comment]
It should automatically update the formula whenever you publish a new release on GitHub, with no additional work required on your part.

**Comment by kraanzu** [comment]
Awesome! Great work <3

**Comment by Abeautifulsnow** [comment]
@@superatomic @kraanzu  Hello, it looks like something goes wrong here. I can't install `dooit` with the Homebrew tool. 

```bash
➜  ~ brew install dooit
Running `brew update --preinstall`...
Warning: No available formula with the name "dooit".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

➜  ~ brew search dooit
Error: No formulae or casks found for "dooit".
```

Based on your conversation, `brew install dooit` should work normally now. 😊 
Looking forward to your reply.  THX. ^_^

**Comment by superatomic** [comment]
@Abeautifulsnow Can you try running `brew update` and trying it again? There's a possibility that you just need to pull in the newest formulae.

**Comment by Abeautifulsnow** [comment]
@superatomic Thank you for your help. The`brew update` command worked for me, and then I successfully installed `dooit`.

**Pull request merged**
