### PR TITLE
changed status bar date format

### PR DESCRIPTION
**Pull request by thrombe**
this PR changes the date format in status bar to dd-mm-yyyy from mm-dd-yyyy just to be consistent with due date format
(this is my first PR. let me know if i do someting wrong)

### CODE REVIEW

**Comment by kraanzu** [comment]
Thanks for opening the PR!

>  let me know if i do someting wrong

Have you tried running the updated version in a windows machine?
I used `.format` syntax instead of simple `f-string` because of issue #35 
Here's the [commit](https://github.com/kraanzu/dooit/commit/5c900e23f2055e6dc9cee290c10f43f9bccf0f5e)

**Comment by carsonl** [comment]
My 2c on this is to prefer YYYY-MM-DD everywhere.

That way it can be understood by all.

Is 05/07 the 5th of July or 7th of May?

**Comment by thrombe** [comment]
@kraanzu ,
i tested it on a windows 11 kvm and it seems to work just fine.
while doing the following still fails with the same error as #35 
```f"{datetime.today().strftime(f' {self.calendar_icon}  %d/%m/%Y ')}"```.
i guess this is because the ```self.calender_icon``` icon is passed into ```strftime``` unlike what is done in this PR

**Comment by kraanzu** [comment]
Hey @thrombe,
Sorry for the late reply.. I am currently dealing with my uni exams.
Thanks for the work!  I'll merge this now :)

**Comment by kraanzu** [comment]
Hey @carsonl ,
> My 2c on this is to prefer YYYY-MM-DD everywhere.

I can do this but since everyone has started using it... I'll keep the `DD-MM-YYYY` format for now to avoid any confusion.

> That way it can be understood by all.

I suppose DDMMYYYY is pretty common too
So ig I'll keep this as it is for now :)

**Comment by kraanzu** [comment]
> You could also probably just detect the person's locale and display their preferred date format (I think python can do that)

Yes I can do that, I  promise to look into it later :)

**Pull request merged**
